version: "3.8"

services:
  dog-server:
    build: ./dog-server/
    container_name: 'dog-container'
    volumes:
      - ./dog-server/html/:/usr/share/nginx/html
    ports: 
      - 7000:80
  cat-server:
    build: ./cat-server/
    container_name: 'cat-container'
    volumes:
      - ./cat-server/html/:/usr/share/nginx/html
    ports: 
      - 7001:80
  modsecurity:
    build: ./modsecurity/
    ports:
      - 80:80 
    volumes:
        - ./modsecurity/log/modsec_audit.log:/var/log/modsec_audit.log